[versions]
kotlin = "2.0.0"
#dokka = "1.9.20"
#parcelize = "2.0.0"
#serialization = "2.0.0"
#coroutines = "1.9.0-RC"
compose = "1.6.11"

[libraries]

[plugins]
# Kotlin interop plugin
jetbrains-compose-interop = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
# the actual Compose framework
jetbrains-compose-framework = { id = "org.jetbrains.compose", version.ref = "compose" }

#jetbrains-kotlin-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
#jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
#jetbrains-kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "parcelize" }
#jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
